import { useState, type FormEvent } from "react";
import { Link } from "react-router-dom";
import { FiArrowLeft, FiPlus, FiSave, FiTrash2 } from "react-icons/fi";
import { useStudioDemo } from "../../../contexts/StudioDemoContext";
import type { Course, MemberPlan } from "../../../types/member";
import type { StudioFeature } from "../../../types/danceStudio.types";

function CourseEditor({ course, onSave, onRemove }: { course: Course; onSave: (course: Course) => void; onRemove: () => void }) {
  const [draft, setDraft] = useState(course);
  const date = new Date(draft.startsAt);
  const localDate = new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16);
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); onSave(draft); }
  return <form className="podium-editor" onSubmit={submit}><label>Prestation<input required value={draft.title} maxLength={80} onChange={e => setDraft({ ...draft, title: e.target.value })} /></label><label>Niveau<input required value={draft.level} onChange={e => setDraft({ ...draft, level: e.target.value })} /></label><label>Début du cours · heure de cet appareil<input required type="datetime-local" value={localDate} onChange={e => { const value = new Date(e.target.value); if (!Number.isNaN(value.getTime())) setDraft({ ...draft, startsAt: value.toISOString() }); }} /></label><label>Durée en minutes<input required type="number" min="15" max="240" step="15" value={draft.duration} onChange={e => setDraft({ ...draft, duration: Number(e.target.value) })} /></label><label>Capacité<input required type="number" min={Math.max(1, draft.occupied)} max="50" value={draft.capacity} onChange={e => setDraft({ ...draft, capacity: Number(e.target.value) })} /></label><div className="podium-editor__actions"><button type="submit"><FiSave aria-hidden="true" /> Enregistrer le cours</button><button type="button" onClick={onRemove}><FiTrash2 aria-hidden="true" /> Supprimer</button></div></form>;
}
function PlanEditor({ plan, onSave }: { plan: MemberPlan; onSave: (plan: MemberPlan) => void }) {
  const [draft, setDraft] = useState(plan);
  return <form className="podium-editor" onSubmit={e => { e.preventDefault(); onSave(draft); }}><label>Nom du carnet<input required value={draft.name} maxLength={80} onChange={e => setDraft({ ...draft, name: e.target.value })} /></label><label>Prix en euros<input required type="number" min="1" max="10000" step="0.01" value={draft.price} onChange={e => setDraft({ ...draft, price: Number(e.target.value) })} /></label><label>Nombre de crédits<input required type="number" min="1" max="100" value={draft.credits} onChange={e => setDraft({ ...draft, credits: Number(e.target.value) })} /></label><label>Description<textarea required value={draft.description} maxLength={400} onChange={e => setDraft({ ...draft, description: e.target.value })} /></label><button type="submit"><FiSave aria-hidden="true" /> Enregistrer le carnet</button></form>;
}
function ServiceEditor({ service, onSave }: { service: StudioFeature; onSave: (service: StudioFeature) => void }) {
  const [draft, setDraft] = useState(service);
  return <form className="podium-editor" onSubmit={e => { e.preventDefault(); onSave(draft); }}><label>Prestation<input required maxLength={80} value={draft.title} onChange={e => setDraft({ ...draft, title: e.target.value })} /></label><label>Présentation<textarea required maxLength={400} value={draft.text} onChange={e => setDraft({ ...draft, text: e.target.value })} /></label><button type="submit"><FiSave aria-hidden="true" /> Enregistrer la prestation</button></form>;
}
export function AdminDemoPage() {
  const studio = useStudioDemo();
  const [tab, setTab] = useState<"courses" | "plans" | "services">("courses");
  const [limit, setLimit] = useState(3);
  function addCourse() { const date = new Date(); date.setDate(date.getDate() + 7); date.setHours(19, 0, 0, 0); studio.save({ ...studio, courses: [{ id: `demo-${crypto.randomUUID()}`, title: "Nouveau cours", level: "Débutant", instructor: "Équipe Le Podium · démo", startsAt: date.toISOString(), duration: 60, capacity: 8, occupied: 0, room: "Studio Le Podium" }, ...studio.courses] }); }
  return <main className="podium-admin"><Link to="/" className="podium-back"><FiArrowLeft aria-hidden="true" /> Retour au site</Link><p className="studio-label">Administration · maquette publique</p><h1>Le studio, à votre main.</h1><div className="podium-warning"><strong>Cette page n’est pas un back-office sécurisé.</strong><p>Elle illustre les outils de gestion avec des données fictives et locales. Ne saisissez aucune donnée d’adhérente. Les modifications ne concernent que ce navigateur, jamais le vrai studio. L’accès gérante avec permissions serveur sera livré dans la phase backend.</p></div><nav aria-label="Administration de démonstration">{([['courses','Planning'],['plans','Carnets & tarifs'],['services','Prestations']] as const).map(([id,label]) => <button key={id} aria-pressed={tab === id} onClick={() => setTab(id)}>{label}</button>)}</nav>{studio.notice && <p role="status" className="podium-warning">{studio.notice}</p>}
    {tab === "courses" && <section><div className="podium-admin__heading"><h2>Planning fictif</h2><button onClick={addCourse}><FiPlus aria-hidden="true" /> Ajouter un cours</button></div>{studio.courses.slice(0, limit).map(course => <CourseEditor key={`${course.id}-${course.startsAt}`} course={course} onSave={updated => studio.save({ ...studio, courses: studio.courses.map(item => item.id === updated.id ? updated : item) })} onRemove={() => studio.save({ ...studio, courses: studio.courses.filter(item => item.id !== course.id) })} />)}{limit < studio.courses.length && <button onClick={() => setLimit(limit + 5)}>Afficher les cours suivants</button>}<Link to="/account">Voir le planning adhérent</Link></section>}
    {tab === "plans" && <section><h2>Carnets · paiement désactivé</h2>{studio.plans.map(plan => <PlanEditor key={plan.id} plan={plan} onSave={updated => studio.save({ ...studio, plans: studio.plans.map(item => item.id === updated.id ? updated : item) })} />)}<p>Stripe est préparé dans le dépôt, mais aucun paiement n’est actif. Les abonnements récurrents seront intégrés au backend après validation des contrats et du compte Stripe du studio.</p></section>}
    {tab === "services" && <section><div className="podium-admin__heading"><h2>Prestations de la vitrine</h2><button onClick={() => studio.save({ ...studio, services: [...studio.services, { number: String(studio.services.length + 1).padStart(2, '0'), title: "Nouvelle prestation", text: "Présentation de démonstration à modifier." }] })}><FiPlus aria-hidden="true" /> Ajouter une prestation</button></div>{studio.services.map(service => <ServiceEditor key={service.number} service={service} onSave={updated => studio.save({ ...studio, services: studio.services.map(item => item.number === updated.number ? updated : item) })} />)}</section>}
    <details className="podium-reset"><summary>Réinitialiser la configuration de démonstration</summary><p>Cette action remplace vos essais de planning, de tarifs et de prestations par les valeurs initiales. Les réservations du compte fictif restent distinctes.</p><button onClick={studio.reset}>Confirmer la réinitialisation locale</button></details></main>;
}
