import { useEffect, useRef, useState, type FormEvent } from "react";
import { Link } from "react-router-dom";
import { FiArrowLeft, FiArrowRight, FiCalendar, FiCheck, FiCreditCard, FiUser, FiX, FiRefreshCw, FiClock } from "react-icons/fi";
import { memberContent } from "../../../content/member";
import { useMemberAccount } from "../../../hooks/useMemberAccount";
import type { AccountTab, Course, MemberProfile } from "../../../types/member";
import "./memberAccount.scss";
import { useDemoSession } from "../../../contexts/DemoSessionContext";

const money = (value: number) => new Intl.NumberFormat("fr-FR", { style: "currency", currency: "EUR", maximumFractionDigits: 0 }).format(value);
const dateLabel = (date: string) => new Intl.DateTimeFormat("fr-FR", { weekday: "short", day: "numeric", month: "short", timeZone: "Europe/Paris" }).format(new Date(date));
const timeLabel = (date: string) => new Intl.DateTimeFormat("fr-FR", { hour: "2-digit", minute: "2-digit", timeZone: "Europe/Paris" }).format(new Date(date));

function ProfileForm({ profile, onSave }: { profile: MemberProfile; onSave: (profile: MemberProfile) => void }) {
  const [draft, setDraft] = useState(profile);
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); onSave(draft); }
  return <form className="member-form" onSubmit={submit}><h2>Mes coordonnées</h2><p>Informations fictives pour la démonstration.</p>{([{ key: "firstName", label: "Prénom" }, { key: "lastName", label: "Nom" }, { key: "email", label: "Email" }, { key: "phone", label: "Téléphone" }, { key: "emergencyContact", label: "Contact en cas d’urgence" }] as const).map(field => <label key={field.key}>{field.label}<input required={field.key !== "emergencyContact"} type={field.key === "email" ? "email" : field.key === "phone" ? "tel" : "text"} value={draft[field.key]} onChange={event => setDraft({ ...draft, [field.key]: event.target.value })} /></label>)}<label className="member-checkbox"><input type="checkbox" checked={draft.notifications} onChange={event => setDraft({ ...draft, notifications: event.target.checked })} />Recevoir les rappels de cours et les nouvelles du club</label><button className="member-primary">Enregistrer mes informations</button></form>;
}

export function MemberAccountPage() {
  const account = useMemberAccount();
  const session = useDemoSession();
  const { state, plan, courses } = account;
  const [tab, setTab] = useState<AccountTab>("schedule");
  const [filter, setFilter] = useState("Tous");
  const [dayFilter, setDayFilter] = useState("all");
  const [confirmation, setConfirmation] = useState<{ title: string; text: string; action: () => void }>();
  const modalRef = useRef<HTMLDivElement>(null);
  useEffect(() => {
    if (!confirmation) return;
    const previous = document.activeElement;
    function keyboard(event: KeyboardEvent) {
      if (event.key === "Escape") setConfirmation(undefined);
      if (event.key !== "Tab") return;
      const buttons = modalRef.current?.querySelectorAll<HTMLButtonElement>("button");
      if (!buttons?.length) return;
      const first = buttons[0]; const last = buttons[buttons.length - 1];
      if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); }
      else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); }
    }
    document.addEventListener("keydown", keyboard);
    return () => { document.removeEventListener("keydown", keyboard); if (previous instanceof HTMLElement) previous.focus(); };
  }, [confirmation]);
  const active = state.enrollments.filter(item => item.status === "confirmed" || item.status === "waiting");
  const next = courses.find(course => active.some(item => item.courseId === course.id && item.status === "confirmed"));
  const days = [...new Set(courses.map(course => course.startsAt.slice(0, 10)))];
  function courseCard(course: Course) {
    const enrollment = state.enrollments.find(item => item.courseId === course.id && item.status !== "cancelled");
    const full = course.occupied >= course.capacity;
    return <article className="member-course" key={course.id}><div className="member-course__date"><strong>{timeLabel(course.startsAt)}</strong><span>{dateLabel(course.startsAt)}</span></div><div><div className="member-badges"><span>{course.level}</span>{full ? <span className="member-badge--warm">Complet</span> : <span>{course.capacity - course.occupied} places disponibles</span>}</div><h3>{course.title}</h3><p>{course.instructor} · {course.room} · {course.duration} min</p></div>{enrollment ? <div className="member-course__actions"><span className="member-status"><FiCheck />{enrollment.status === "waiting" ? "Liste d’attente" : "Réservé"}</span><button onClick={() => setConfirmation({ title: "Annuler ce cours ?", text: `Le crédit est restitué si vous annulez au moins ${memberContent.cancellationHours}h avant le début.`, action: () => account.cancel(course) })}>Annuler</button></div> : <button className="member-primary" disabled={!full && state.credits < 1} onClick={() => account.enroll(course)}>{full ? "Rejoindre l’attente" : "Réserver · 1 crédit"}</button>}</article>;
  }
  return <main className="member-account"><header className="member-top"><Link to="/"><FiArrowLeft /> Retour au site</Link><strong>{memberContent.brand}<span>{memberContent.subtitle}</span></strong><button onClick={session.signOut}>Quitter la démo</button></header><div className="member-demo">Démo interactive · compte fictif · données conservées uniquement dans ce navigateur · aucun paiement réel</div><div className="member-shell"><aside className="member-sidebar"><p>MON CLUB</p><nav aria-label="Espace adhérent">{memberContent.tabs.map(item => <button className={tab === item.id ? "is-active" : ""} aria-current={tab === item.id ? "page" : undefined} key={item.id} onClick={() => setTab(item.id)}>{item.id === "schedule" || item.id === "bookings" ? <FiCalendar /> : item.id === "billing" || item.id === "membership" ? <FiCreditCard /> : <FiUser />}{item.label}</button>)}</nav><div className="member-sidebar__balance"><span>Votre réserve d’énergie</span><strong>{state.credits} crédits</strong><button onClick={() => setTab("membership")}>Gérer mon adhésion <FiArrowRight aria-hidden="true" /></button></div><button className="member-reset" onClick={() => setConfirmation({ title: "Rejouer la démonstration ?", text: "Les réservations, crédits et coordonnées retrouveront leurs valeurs initiales.", action: account.reset })}><FiRefreshCw /> Réinitialiser la démo</button></aside><section className="member-main"><div className="member-page-title"><p>ESPACE ADHÉRENT</p><h1>{tab === "overview" ? `Bonjour ${state.profile.firstName}.` : memberContent.tabs.find(item => item.id === tab)?.label}</h1><p>{tab === "overview" ? "Votre prochain cours, votre progression, votre club." : "Tout ce qu’il vous faut pour organiser votre pratique."}</p></div>{account.notice && <div className="member-notice" role="status"><FiCheck />{account.notice}</div>}
    {tab === "overview" && <><div className="member-stats"><article><FiCreditCard /><span>Crédits disponibles</span><strong>{state.credits}</strong><button onClick={() => setTab("membership")}>Recharger</button></article><article><FiCalendar /><span>Inscriptions à venir</span><strong>{active.length}</strong><button onClick={() => setTab("bookings")}>Voir mes cours</button></article><article><FiUser /><span>Ma formule</span><strong className="member-stats__plan">{plan.name}</strong><small>{money(plan.price)} · carnet</small></article></div><div className="member-overview"><article className="member-next"><span className="member-kicker">VOTRE PROCHAIN RENDEZ-VOUS</span>{next ? <><h2>{next.title}</h2><p>{dateLabel(next.startsAt)} à {timeLabel(next.startsAt)} · {next.instructor}</p><span>{next.level} · {next.duration} min</span></> : <><h2>La prochaine séance vous attend.</h2><p>Choisissez un cours dans le planning.</p></>}<button className="member-primary" onClick={() => setTab("schedule")}>Explorer le planning</button></article><article className="member-info"><h2>Bien préparer son cours</h2><p>Prévoyez une tenue adaptée, une bouteille d’eau et arrivez 10 minutes avant le début.</p><p>Pour la pole technique : prévoyez un short, un débardeur et votre tapis d’échauffement.</p><small>Consignes illustratives, à personnaliser avec le club.</small></article></div><article className="member-info"><h2>La vie du club</h2><p>Les créneaux présentés ici illustrent la future expérience adhérente. Retrouvez les cours réels sur le site actuel du Podium.</p></article></>}
    {tab === "schedule" && <><div className="member-filters"><label>Discipline<select value={filter} onChange={event => setFilter(event.target.value)}>{["Tous", ...new Set(courses.map(course => course.title))].map(value => <option key={value}>{value}</option>)}</select></label><label>Jour<select value={dayFilter} onChange={event => setDayFilter(event.target.value)}><option value="all">Toute la semaine</option>{days.map(day => <option value={day} key={day}>{dateLabel(`${day}T12:00:00Z`)}</option>)}</select></label><p><FiClock />Annulation gratuite jusqu’à {memberContent.cancellationHours}h avant</p></div><div className="member-course-list">{courses.filter(course => (filter === "Tous" || course.title === filter) && (dayFilter === "all" || course.startsAt.startsWith(dayFilter))).map(courseCard)}</div></>}
    {tab === "bookings" && <><h2>À venir et listes d’attente</h2><div className="member-course-list">{courses.filter(course => active.some(item => item.courseId === course.id)).map(courseCard)}{active.length === 0 && <p className="member-empty">Aucune inscription pour le moment. Retrouvez vos cours dans le planning.</p>}</div><h2>Historique</h2><div className="member-info">{state.enrollments.filter(item => item.status === "cancelled").map(item => <p key={item.courseId}>{courses.find(course => course.id === item.courseId)?.title} · annulé</p>)}<p>Exemple fictif : Pole débutant · séance suivie · 1 crédit utilisé</p></div></>}
    {tab === "membership" && <><article className="member-info"><h2>{plan.name} · adhésion active</h2><p>{plan.credits} cours dans ce carnet · {money(plan.price)} · carnet · solde actuel : {state.credits} crédits.</p><small>Carnet ponctuel en démonstration. Aucun renouvellement ni prélèvement automatique. La validité réelle sera gérée par le backend.</small></article><h2>Une formule pour votre rythme</h2><div className="member-plans">{account.plans.map(item => <article key={item.id} className={item.id === plan.id ? "is-selected" : ""}><span>{item.id === plan.id ? "MA FORMULE" : `${item.credits} COURS / CARNET`}</span><h3>{item.name}</h3><strong>{money(item.price)}<small> · carnet</small></strong><p>{item.description}</p><button className="member-primary" disabled={item.id === plan.id} onClick={() => setConfirmation({ title: `Activer la formule ${item.name} ?`, text: `${item.credits} crédits seront ajoutés et une transaction fictive de ${money(item.price)} sera créée. Aucun prélèvement réel.`, action: () => account.changePlan(item.id) })}>{item.id === plan.id ? "Formule actuelle" : "Choisir cette formule"}</button></article>)}</div><article className="member-info"><h2>Un peu plus de pratique ?</h2><p>Carnet de {memberContent.extraCredits.quantity} cours · {money(memberContent.extraCredits.price)} · crédits utilisables dans tous les cours de la démo.</p><button className="member-primary" onClick={() => setConfirmation({ title: "Ajouter 5 crédits ?", text: "Une transaction fictive de 90 € sera ajoutée à votre historique.", action: account.topUp })}>Recharger mon carnet</button></article></>}
    {tab === "billing" && <><article className="member-info"><h2>Paiements et justificatifs</h2><p>Retrouvez ici vos adhésions et carnets de cours. Dans cette démonstration, les transactions sont fictives et les justificatifs ne sont pas des documents comptables.</p></article><div className="member-invoices">{state.invoices.map(invoice => <article key={invoice.id}><div><strong>{invoice.label}</strong><p>{dateLabel(invoice.date)} · {invoice.id}</p></div><span className="member-status">Payé · démo</span><strong>{money(invoice.amount)}</strong><button onClick={() => account.downloadInvoice(invoice)}>Télécharger</button></article>)}</div></>}
    {tab === "profile" && <ProfileForm profile={state.profile} onSave={account.saveProfile} />}
  </section></div>{confirmation && <div className="member-modal-backdrop" ref={modalRef}><section className="member-modal" role="dialog" aria-modal="true" aria-labelledby="member-confirm-title"><button aria-label="Fermer" className="member-modal__close" onClick={() => setConfirmation(undefined)}><FiX /></button><h2 id="member-confirm-title">{confirmation.title}</h2><p>{confirmation.text}</p><div><button onClick={() => setConfirmation(undefined)}>Revenir</button><button className="member-primary" autoFocus onClick={() => { confirmation.action(); setConfirmation(undefined); }}>Confirmer</button></div></section></div>}</main>;
}
